spring:
    application:
        name: springcloud-producer
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
            username: root
            password: 123456
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.xiao.springcloudproducer
    configuration:
        map-underscore-to-camel-case: true

server:
    port: 9000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/



