spring:
    application:
        name: springcloud-consumer
server:
    port: 9001

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

feign:
    hystrix:
        enabled: true